//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeRates.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeRates.Languages.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banknote Buying.
        /// </summary>
        internal static string banknoteBuying {
            get {
                return ResourceManager.GetString("banknoteBuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banknote Selling.
        /// </summary>
        internal static string banknoteSelling {
            get {
                return ResourceManager.GetString("banknoteSelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Rate.
        /// </summary>
        internal static string crossRate {
            get {
                return ResourceManager.GetString("crossRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Rates.
        /// </summary>
        internal static string crossRates {
            get {
                return ResourceManager.GetString("crossRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        internal static string currencyCode {
            get {
                return ResourceManager.GetString("currencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex Buying.
        /// </summary>
        internal static string forexBuying {
            get {
                return ResourceManager.GetString("forexBuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex Selling.
        /// </summary>
        internal static string forexSelling {
            get {
                return ResourceManager.GetString("forexSelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Information.
        /// </summary>
        internal static string forInformation {
            get {
                return ResourceManager.GetString("forInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCMB Rates.
        /// </summary>
        internal static string formTitle {
            get {
                return ResourceManager.GetString("formTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
    }
}
